# Generated by Django 6.0.1 on 2026-02-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('achievement', models.CharField(help_text='e.g. NEET AIR 50, IIT Bombay CSE', max_length=200)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='counselors/')),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='Link to WhatsApp or booking form')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselors', to='guidance.examcategory')),
            ],
        ),
    ]
